---
- name: 'Install Apache2'
  hosts: 'all'
  gather_facts: true
  become: true

  roles:
    - role: 'johanneskastl.install_one_or_more_packages'
      packages_to_be_installed:
        - apache2
        - apache2-utils
